services:
    elasticsearch:
        image: elasticsearch:7.14.0
        hostname: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
        networks:
            - elastic
        volumes:
            - elastic-data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.14.0
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elastic

networks:
    elastic:
        driver: bridge

volumes:
    elastic-data:
        driver: local