icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#151515"
idle_fg = "#EEE8D5"
info_bg = "#2ECC71"
info_fg = "#2B2C2B"


[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp59s0"
ip = true
speed_up = false
speed_down = false
hide_missing = true
hide_inactive = true
bitrate = true

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"
